### ISSUE TITLE
Hide song information at start

### ISSUE THREAD

**Issue by PinkPenguin** [dic15jma/MAMN01#5]
Some people were confused by the fact that the song information layout was visible at start.

Preferably it should only become visible once a song has started playing and after that it can be visible as long as the app is running.

**Comment by TobiasMorell** [comment]
This issue was fixed in commit c2d5489406ec011c54cabfe91888b5ea86d4849d, as the box is simply made invisible when currentSong of the training activitiy's data binding is set to null.
